src/app.css, src/app.html, src/routes/_timer.svelte, src/routes/_timer_segment.svelte, src/routes/index.svelte, tailwind.config.cjs
This PR reworks the font families and color scheme of the site to fit with the Overwatch aesthetic.
=> feat: Visual overhaul

src/app.css, src/app.html, src/routes/_timer.svelte, src/routes/index.svelte, tailwind.config.cjs
This PR add the ability to use a query parameter to set the theme of the site, as well as a display for the local time.
=> Local time and fades

src/routes/_timer.svelte, src/routes/_timer_segment.svelte, src/routes/index.svelte, src/stores/dates.ts
When the time remaining falls beneath the granularity of a certain unit, this PR will make the timer transition that element out.
=> feat: Add nice transition when unit is depleted

package.json, src/routes/_timer.svelte, src/routes/_timer_segment.svelte, src/routes/index.svelte, src/stores/dates.ts, yarn.lock
- chore: Add absolute timestamp example to date stub
- style: properly indent chained method calls
- feat: multiple countdown timers
- feat: Add confetti when a timer is up
=> multi countdown

src/routes/_copy_time.svelte, src/routes/_copy_time_button.svelte, src/routes/_dropdown_item.svelte, src/routes/index.svelte, yarn.lock
This PR adds a button which copies the date and time as-is
=> feat: Add copy for just the date

src/routes/sitemap.xml/+server.ts
To aid search engines in crawling the entirety of OW2Countdown, this PR adds a `sitemap.xml` route.
=> feat: Add sitemap.xml

src/lib/components/_timer.svelte, src/lib/components/_timer_segment.svelte, src/routes/api/events/+server.ts
- style: Remove commented-out legacy code
- feat: Make blank timer pulse
=> feat: Pulsing timer when start/end dates are not defined

.gitignore, README.md, package.json, src/app.d.ts, src/hooks.client.ts, src/hooks.server.ts, src/lib/client.ts, src/lib/components/event/_form.svelte, src/lib/database.types.ts, src/lib/db.ts, src/lib/types.d.ts, src/routes/+layout.server.ts, src/routes/+layout.svelte, src/routes/+layout.ts, src/routes/+page.svelte, src/routes/_event_card.svelte, src/routes/api/event/[id]/+server.ts, src/routes/event/[id]/+page.server.ts, src/routes/event/[id]/[slug]/+page.svelte, src/routes/event/[id]/destroy/+page.server.ts, src/routes/event/[id]/edit/+page.server.ts, src/routes/event/[id]/edit/+page.svelte, src/routes/event/[id]/edit/+page.ts, src/routes/event/new/+page.server.ts, src/routes/event/new/+page.svelte, src/routes/login/+page.svelte, src/routes/logout/+page.svelte, src/stores/dates.ts, yarn.lock
This PR adds administrative functionality to OW2Countdown, including creating, editing, and deleting events.
=> feat: Admin actions

.gitignore, src/lib/components/_dropdown.svelte, src/routes/_event_card.svelte, src/routes/event/[id]/[slug]/+layout.svelte
To make the user interface feel more responsive, this PR adds background color transitions on buttons which can be clicked
=> feat: Add animated background colors to some elements

src/lib/components/event/_form.svelte, src/routes/event/[id]/[slug]/+error.svelte, src/routes/event/[id]/edit/+page.svelte, src/routes/event/new/+page.svelte
- fix: Correctly load existing tags
- chore: Indicate to web crawlers that 404 is a 404
- fix: Properly process end_date field
=> chore: Fix post form and add 404 indicator

src/lib/components/_dropdown.svelte, src/lib/components/_timer.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/_event_card.svelte, src/routes/event/[id]/[slug]/+layout.svelte, src/routes/event/[id]/[slug]/+page.svelte
This PR adds better page transitions and fixes a bug with the post show page
=> better transitions

package.json, src/lib/webVitals.ts, src/routes/+layout.svelte, src/routes/privacy-policy/+page.svelte, yarn.lock
This PR adds anonymized analytics via Vercel Analytics to better understand how the site is used and how it is performing.
=> feat: Vercel Analytics

package.json, src/hooks.client.ts, src/routes/privacy-policy/+page.svelte, yarn.lock
To track general visitor trends and user demographics
=> feat: Add Audiences from Vercel

src/app.html, src/lib/components/_dropdown.svelte, src/routes/+page.svelte, src/routes/_event_card.svelte, src/routes/event/[id]/[slug]/+layout.svelte, src/routes/event/[id]/[slug]/+page.svelte
- perf: Pre-load links on hover
- feat: More appealing button styling
- fix: Prevent jumping of loading/no events message when transitioning back to homepage
- feat: Add fade transition to centered messages
=> misc site improvements

src/routes/+page.svelte, src/routes/login/+page.svelte, src/routes/logout/+page.svelte
=> email auth

src/routes/+page.svelte, src/routes/event/+layout.svelte, src/routes/event/[id]/[slug]/+page.svelte
This PR fixes some alignment issues caused by the previous refactoring of the site.
=> fix alignment issues

src/routes/event/[id]/[slug]/embed/_embed.svelte
This PR adds spacing between the progress bar and the timer in embeds, while also limiting the width of the progress bar in the same location.
=> adjust embed appearance

src/routes/api/events/+server.ts
Fixes the `include_past` and `page` query params on the events API.
=> fix: include_past and page query params on events api

src/routes/about/+page.svelte
=> Update `/about` page

src/routes/(app)/+page.svelte, src/routes/(app)/event/[id]/[slug]/+page.svelte, src/routes/(app)/event/[id]/edit/+page.svelte, src/routes/(app)/event/new/+page.svelte
- **fix: new event button was too big**
- **fix: ensure event forms can be submitted**
=> fix: regressions

src/routes/+layout.ts
- **fix: incorrect loading of vercel insights**
=> fix: incorrect vercel speed insights load
